engine:
  - prefix: "front_left"
    position: "1.1 1 0"
    orientation: "0.0 0.0 0"
  - prefix: "front_right"
    position: "1.1 -1 0"
    orientation: "0.0 0.0 0"
  - prefix: "back_left"
    position: "-2.4 1 0"
    orientation: "0.0 0.0 0"
  - prefix: "back_right"
    position: "-2.4 -1 0"
    orientation: "0.0 0.0 0"